-- MySQL Script generated by MySQL Workbench
-- Thu Jan  4 11:23:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Laboratorio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Laboratorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Laboratorio` DEFAULT CHARACTER SET utf8 ;
USE `Laboratorio` ;

-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Paciente` (
  `IdPaciente` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `FechaNac` DATE NOT NULL,
  `FechaIn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Sexo` CHAR NOT NULL DEFAULT 'M',
  `Celular` VARCHAR(15) NOT NULL DEFAULT 'NO INGRESADO',
  `Correo` VARCHAR(75) NOT NULL DEFAULT 'NO INGRESADO',
  `Direccion` VARCHAR(255) NOT NULL DEFAULT 'NO INGRESADO',
  PRIMARY KEY (`IdPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Remitente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Remitente` (
  `IdRemitente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(70) NOT NULL,
  `Tel/Cel` VARCHAR(15) NOT NULL DEFAULT 'NO INGRESADO',
  `Correo` VARCHAR(45) NOT NULL DEFAULT 'NO INGRESADO',
  PRIMARY KEY (`IdRemitente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Empleado` (
  `IdEmpleado` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `FechaIn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FechaNac` DATE NOT NULL,
  `Celular` VARCHAR(15) NOT NULL DEFAULT 'NO INGRESADO',
  `Direccion` VARCHAR(255) NOT NULL DEFAULT 'NO INGRESADO',
  `Correo` VARCHAR(70) NOT NULL DEFAULT 'NO INGRESADO',
  PRIMARY KEY (`IdEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Orden` (
  `IdOrden` INT NOT NULL AUTO_INCREMENT,
  `FechaIngreso` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FPrint` DATETIME NULL,
  `IdPaciente` INT NOT NULL,
  `IdRemitente` INT NOT NULL,
  `IdEmpleado` INT NOT NULL,
  PRIMARY KEY (`IdOrden`),
  INDEX `fk_tbl_Orden_tbl_Paciente_idx` (`IdPaciente` ASC),
  INDEX `fk_tbl_Orden_tbl_Remitente1_idx` (`IdRemitente` ASC),
  INDEX `fk_tbl_Orden_tbl_Empleado1_idx` (`IdEmpleado` ASC),
  CONSTRAINT `fk_tbl_Orden_tbl_Paciente`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `Laboratorio`.`tbl_Paciente` (`IdPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Orden_tbl_Remitente1`
    FOREIGN KEY (`IdRemitente`)
    REFERENCES `Laboratorio`.`tbl_Remitente` (`IdRemitente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Orden_tbl_Empleado1`
    FOREIGN KEY (`IdEmpleado`)
    REFERENCES `Laboratorio`.`tbl_Empleado` (`IdEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_TipoExamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_TipoExamen` (
  `IdTipo` INT NOT NULL,
  `NombreTipo` VARCHAR(45) NULL,
  PRIMARY KEY (`IdTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Examenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Examenes` (
  `IdExamen` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `ValRef` VARCHAR(45) NULL,
  `Unidades` VARCHAR(45) NULL,
  `tbl_TipoExamen_IdTipo` INT NOT NULL,
  PRIMARY KEY (`IdExamen`),
  INDEX `fk_tbl_Examenes_tbl_TipoExamen1_idx` (`tbl_TipoExamen_IdTipo` ASC),
  CONSTRAINT `fk_tbl_Examenes_tbl_TipoExamen1`
    FOREIGN KEY (`tbl_TipoExamen_IdTipo`)
    REFERENCES `Laboratorio`.`tbl_TipoExamen` (`IdTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Alteraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Alteraciones` (
  `IdAlteracion` INT NOT NULL AUTO_INCREMENT,
  `NombreAlte` VARCHAR(45) NOT NULL,
  `TipoAlt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdAlteracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Tiempos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Tiempos` (
  `IdTiempos` INT NOT NULL,
  `TP_Paciente` VARCHAR(45) NULL,
  `TP_Control` VARCHAR(45) NULL,
  `TTP_Paciente` VARCHAR(45) NULL,
  `TTP_Control` VARCHAR(45) NULL,
  `INR` VARCHAR(45) NULL,
  `tbl_Orden_IdOrden` INT NOT NULL,
  `Validado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`IdTiempos`),
  INDEX `fk_tbl_Tiempos_tbl_Orden1_idx` (`tbl_Orden_IdOrden` ASC),
  CONSTRAINT `fk_tbl_Tiempos_tbl_Orden1`
    FOREIGN KEY (`tbl_Orden_IdOrden`)
    REFERENCES `Laboratorio`.`tbl_Orden` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Uroanalisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Uroanalisis` (
  `IdUroanalisis` INT NOT NULL AUTO_INCREMENT,
  `Color` VARCHAR(45) NULL DEFAULT 'AMARILLO',
  `Olor` VARCHAR(45) NULL DEFAULT 'SUIGENERIS',
  `Aspecto` VARCHAR(45) NULL,
  `Densidad` VARCHAR(45) NULL,
  `PH` VARCHAR(45) NULL,
  `Glucosa` VARCHAR(45) NULL,
  `Proteinas` VARCHAR(45) NULL,
  `Sangre` VARCHAR(45) NULL,
  `Cetonas` VARCHAR(45) NULL,
  `Urobilinogeno` VARCHAR(45) NULL,
  `Bilirrubina` VARCHAR(45) NULL,
  `Nitritos` VARCHAR(45) NULL,
  `LeucocitosQ` VARCHAR(45) NULL,
  `CelulasEpiteliales` VARCHAR(45) NULL,
  `Eritrocitos` VARCHAR(45) NULL,
  `Leucocitos` VARCHAR(45) NULL,
  `Bacterias` VARCHAR(45) NULL,
  `Levaduras` VARCHAR(45) NULL,
  `Moco` VARCHAR(45) NULL,
  `Cilindros` VARCHAR(45) NULL,
  `Cristales` VARCHAR(45) NULL,
  `Parasitos` VARCHAR(45) NULL,
  `Observacion 1` VARCHAR(45) NULL,
  `Observacion 2` VARCHAR(45) NULL,
  `Observacion 3` VARCHAR(45) NULL,
  `Validado` VARCHAR(45) NULL,
  `tbl_Orden_IdOrden` INT NOT NULL,
  PRIMARY KEY (`IdUroanalisis`),
  INDEX `fk_tbl_Uroanalisis_tbl_Orden1_idx` (`tbl_Orden_IdOrden` ASC),
  CONSTRAINT `fk_tbl_Uroanalisis_tbl_Orden1`
    FOREIGN KEY (`tbl_Orden_IdOrden`)
    REFERENCES `Laboratorio`.`tbl_Orden` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`Examenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`Examenes` (
  `IdOrden` INT NOT NULL,
  `IdExamen` INT NOT NULL,
  `Resultado` VARCHAR(45) NOT NULL,
  `Validado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdOrden`, `IdExamen`),
  INDEX `fk_tbl_Orden_has_tbl_Examenes_tbl_Examenes1_idx` (`IdExamen` ASC),
  INDEX `fk_tbl_Orden_has_tbl_Examenes_tbl_Orden1_idx` (`IdOrden` ASC),
  CONSTRAINT `fk_tbl_Orden_has_tbl_Examenes_tbl_Orden1`
    FOREIGN KEY (`IdOrden`)
    REFERENCES `Laboratorio`.`tbl_Orden` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Orden_has_tbl_Examenes_tbl_Examenes1`
    FOREIGN KEY (`IdExamen`)
    REFERENCES `Laboratorio`.`tbl_Examenes` (`IdExamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Frotis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Frotis` (
  `IdFrotis` INT NOT NULL,
  `Plaquetas` VARCHAR(45) NULL,
  `Neutrofilos` VARCHAR(45) NULL,
  `Linfositos` VARCHAR(45) NULL,
  `Eosinofilos` VARCHAR(45) NULL,
  `Basofilos` VARCHAR(45) NULL,
  `Monositos` VARCHAR(45) NULL,
  `Linfoblastos` VARCHAR(45) NULL,
  `tbl_Orden_IdOrden` INT NOT NULL,
  PRIMARY KEY (`IdFrotis`),
  INDEX `fk_tbl_Frotis_tbl_Orden1_idx` (`tbl_Orden_IdOrden` ASC),
  CONSTRAINT `fk_tbl_Frotis_tbl_Orden1`
    FOREIGN KEY (`tbl_Orden_IdOrden`)
    REFERENCES `Laboratorio`.`tbl_Orden` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`Alteraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`Alteraciones` (
  `IdFrotis` INT NOT NULL,
  `IdAlteracion` INT NOT NULL,
  `Cruz` VARCHAR(45) NULL,
  PRIMARY KEY (`IdFrotis`, `IdAlteracion`),
  INDEX `fk_tbl_Frotis_has_tbl_Alteraciones_tbl_Alteraciones1_idx` (`IdAlteracion` ASC),
  INDEX `fk_tbl_Frotis_has_tbl_Alteraciones_tbl_Frotis1_idx` (`IdFrotis` ASC),
  CONSTRAINT `fk_tbl_Frotis_has_tbl_Alteraciones_tbl_Frotis1`
    FOREIGN KEY (`IdFrotis`)
    REFERENCES `Laboratorio`.`tbl_Frotis` (`IdFrotis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Frotis_has_tbl_Alteraciones_tbl_Alteraciones1`
    FOREIGN KEY (`IdAlteracion`)
    REFERENCES `Laboratorio`.`tbl_Alteraciones` (`IdAlteracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Parasitologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Parasitologia` (
  `IdParasitologia` INT NOT NULL,
  `Color` VARCHAR(45) NULL,
  `Consistencia` VARCHAR(45) NULL,
  `Moco` VARCHAR(45) NULL,
  `Sangre` VARCHAR(45) NULL,
  `Observacion 1` VARCHAR(45) NULL,
  `Observacion 2` VARCHAR(45) NULL,
  `Observacion 3` VARCHAR(45) NULL,
  `tbl_Orden_IdOrden` INT NOT NULL,
  `Validado` TINYINT(1) NULL,
  PRIMARY KEY (`IdParasitologia`),
  INDEX `fk_tbl_Parasitologia_tbl_Orden1_idx` (`tbl_Orden_IdOrden` ASC),
  CONSTRAINT `fk_tbl_Parasitologia_tbl_Orden1`
    FOREIGN KEY (`tbl_Orden_IdOrden`)
    REFERENCES `Laboratorio`.`tbl_Orden` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Parasito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Parasito` (
  `IdParasito` INT NOT NULL,
  `NombreP` VARCHAR(45) NULL,
  PRIMARY KEY (`IdParasito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`Parasitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`Parasitos` (
  `IdParasitologia` INT NOT NULL,
  `IdParasito` INT NOT NULL,
  `Cruces` VARCHAR(45) NULL,
  `Estadio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdParasitologia`, `IdParasito`, `Estadio`),
  INDEX `fk_tbl_Parasitologia_has_tbl_Parasito_tbl_Parasito1_idx` (`IdParasito` ASC),
  INDEX `fk_tbl_Parasitologia_has_tbl_Parasito_tbl_Parasitologia1_idx` (`IdParasitologia` ASC),
  CONSTRAINT `fk_tbl_Parasitologia_has_tbl_Parasito_tbl_Parasitologia1`
    FOREIGN KEY (`IdParasitologia`)
    REFERENCES `Laboratorio`.`tbl_Parasitologia` (`IdParasitologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Parasitologia_has_tbl_Parasito_tbl_Parasito1`
    FOREIGN KEY (`IdParasito`)
    REFERENCES `Laboratorio`.`tbl_Parasito` (`IdParasito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Citologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Citologia` (
  `IdCitologia` INT NOT NULL AUTO_INCREMENT,
  `CalidadMuestra` VARCHAR(45) NULL,
  `Inflamacion` VARCHAR(45) NULL,
  `Microorganisno` VARCHAR(45) NULL,
  `CambioReprReac` VARCHAR(45) NULL,
  `AnorCelulares` VARCHAR(45) NULL,
  `Resultado1` VARCHAR(45) NULL,
  `Tratamiento` VARCHAR(45) NULL,
  `Observacion 1` VARCHAR(45) NULL,
  `Observacion 2` VARCHAR(45) NULL,
  `tbl_Orden_IdOrden` INT NOT NULL,
  PRIMARY KEY (`IdCitologia`),
  INDEX `fk_tbl_Citologia_tbl_Orden1_idx` (`tbl_Orden_IdOrden` ASC),
  CONSTRAINT `fk_tbl_Citologia_tbl_Orden1`
    FOREIGN KEY (`tbl_Orden_IdOrden`)
    REFERENCES `Laboratorio`.`tbl_Orden` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Bacteriologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Bacteriologia` (
  `IdBacter` INT NOT NULL,
  `TipoCultivo` VARCHAR(45) NULL,
  `NColonias` VARCHAR(45) NULL,
  `TipoBacteria` VARCHAR(45) NULL,
  `Observacion_1` VARCHAR(45) NULL,
  `Observacion_2` VARCHAR(45) NULL,
  `Observacion_3` VARCHAR(45) NULL,
  `tbl_Orden_IdOrden` INT NOT NULL,
  PRIMARY KEY (`IdBacter`),
  INDEX `fk_tbl_Bacteriologia_tbl_Orden1_idx` (`tbl_Orden_IdOrden` ASC),
  CONSTRAINT `fk_tbl_Bacteriologia_tbl_Orden1`
    FOREIGN KEY (`tbl_Orden_IdOrden`)
    REFERENCES `Laboratorio`.`tbl_Orden` (`IdOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`tbl_Antibiotico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`tbl_Antibiotico` (
  `IdAntibiotico` INT NOT NULL,
  `NombreAntibiotico` VARCHAR(45) NULL,
  PRIMARY KEY (`IdAntibiotico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Laboratorio`.`Antibiograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Laboratorio`.`Antibiograma` (
  `IdBacter` INT NOT NULL,
  `IdAntibiotico` INT NOT NULL,
  `Sencible_Resistente` CHAR(1) NOT NULL DEFAULT 'S',
  PRIMARY KEY (`IdBacter`, `IdAntibiotico`),
  INDEX `fk_tbl_Bacteriologia_has_tbl_Antibiotico_tbl_Antibiotico1_idx` (`IdAntibiotico` ASC),
  INDEX `fk_tbl_Bacteriologia_has_tbl_Antibiotico_tbl_Bacteriologia1_idx` (`IdBacter` ASC),
  CONSTRAINT `fk_tbl_Bacteriologia_has_tbl_Antibiotico_tbl_Bacteriologia1`
    FOREIGN KEY (`IdBacter`)
    REFERENCES `Laboratorio`.`tbl_Bacteriologia` (`IdBacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Bacteriologia_has_tbl_Antibiotico_tbl_Antibiotico1`
    FOREIGN KEY (`IdAntibiotico`)
    REFERENCES `Laboratorio`.`tbl_Antibiotico` (`IdAntibiotico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
